modLoader = "javafml"
loaderVersion = "[${loader},)"
license = "${license}"
issueTrackerURL = "https://discord.gg/94Qk4MswX5"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "${authors}"
description = "${description}"
logoFile = "assets/playeremotes/icon.png"
# works with only one side having it, server list must not mark servers without it incompatible
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
